site_name: docu test
site_url: https://fuchsi3010.github.io/docu-test/
theme:
  name: material
  palette:
    scheme: slate
    primary: orange
markdown_extensions:
- pymdownx.tasklist:
    custom_checkbox: true
